const products = [
            {
                id: 1,
                name: 'Vintage Leather Jacket',
                category: 'Apparel',
                price: 189.99,
                image: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=500&fit=crop',
                description: 'Premium quality vintage-style leather jacket perfect for any season.',
            },
            {
                id: 2,
                name: 'Minimalist Coffee Mug',
                category: 'Home Goods',
                price: 15.50,
                image: 'https://images.unsplash.com/photo-1514228742587-6b1558fcf93a?w=400&h=500&fit=crop',
                description: 'Elegant ceramic coffee mug with minimalist design.',
            },
            {
                id: 3,
                name: 'Classic Analog Watch',
                category: 'Accessories',
                price: 120.00,
                image: 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=400&h=500&fit=crop',
                description: 'Timeless analog watch with leather strap and premium movement.',
            },
            {
                id: 4,
                name: 'Wireless Bluetooth Headphones',
                category: 'Electronics',
                price: 75.00,
                image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=500&fit=crop',
                description: 'High-quality wireless headphones with noise cancellation.',
            },
            {
                id: 5,
                name: 'Handcrafted Wooden Bowl',
                category: 'Home Goods',
                price: 45.00,
                image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=500&fit=crop',
                description: 'Beautiful handcrafted wooden bowl perfect for serving.',
            },
            {
                id: 6,
                name: 'Designer Sunglasses',
                category: 'Accessories',
                price: 99.00,
                image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=500&fit=crop',
                description: 'Stylish designer sunglasses with UV protection.',
            },
            {
                id: 7,
                name: 'Ergonomic Desk Chair',
                category: 'Furniture',
                price: 250.00,
                image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=500&fit=crop',
                description: 'Comfortable ergonomic office chair with lumbar support.',
            },
            {
                id: 8,
                name: 'Cotton T-Shirt Pack',
                category: 'Apparel',
                price: 30.00,
                image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=500&fit=crop',
                description: 'Pack of premium cotton t-shirts in various colors.',
            },
            {
                id: 9,
                name: 'Smartphone Case',
                category: 'Electronics',
                price: 25.00,
                image: 'https://images.unsplash.com/photo-1601593346740-925612772716?w=400&h=500&fit=crop',
                description: 'Protective smartphone case with premium materials.',
            },
            {
                id: 10,
                name: 'Modern Table Lamp',
                category: 'Furniture',
                price: 85.00,
                image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=500&fit=crop',
                description: 'Contemporary table lamp with adjustable brightness.',
            },
        ];